services:
  mini-jarvis-docker:
    container_name: mini_jarvis_container
    build: .
    volumes:
      - .:/var/www/html
      - ./node_modules:/var/www/html/node_modules
    ports:
      - "9000:80"
      - "5173:5173"
    depends_on:
      - mysql_docker

  mysql_docker:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: jarvis@123
      MYSQL_DATABASE: mini_jarvis
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "9001:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql_docker

volumes:
  mysql_data:
